name: Docker Image CI

on:
  workflow_dispatch

env:
  IMAGE_NAME: dm1ller/imagine
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push docker image
        run: |
          docker build -t ${{ IMAGE_NAME }}:{{$ IMAGE_TAG }} ./app
          docker push ${{ IMAGE_NAME }}:{{$ IMAGE_TAG }}
