name: Docker Image CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push docker image
        run: |
          TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/imagine:$TIMESTAMP ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/imagine:$TIMESTAMP
