name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Build the Docker image
        run: |
          docker build ./app --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/imagine:$(date +%s)
          docker push ${{ secrets.DOCKER_USERNAME }}/imagine:latest
